scpwiki/sigma

sigma9.css

Users would have the side menus drawn over on mobile when not signed in.  
Changing the menu to top, rather than bottom offset will avoid the issue.

Update css theme for mobile users

---

sigma9.css

There is a proliferation of CSS on the mainsite that attempts to mimic the native quoteblocks created with >. However, many of these divs are not compatible with mobile. Itis possible to add a div class to Sigma-9 that would mimic the native quoteblocks perfectly, and therefore work on mobile and be easy for users to use.
```css
div.blockquote {
border: 1px dashed #999;
background-color: #f4f4f4;
padding: 0 1em;
margin: 1em 3em;
}
@media (max-width: 479px) { 
div.blockquote {
margin: 1em 0;
}
}
@media (min-width: 480px) and (max-width: 580px) { 
div.blockquote {
margin: 0.5em;
}
}
```
Credit to aismallard (@ammongit) for making the code.

Sigma-9 Blockquote Div CSS

---

sigma9.css

As tested in http://scptestwiki.wikidot.com/sigma:topbar
Thanks to @woedenaz 
This PR also strips trailing whitespace. To ignore that and only see the relevant diff, check the following in the cog on the files tab:

Add @media query for topbar fix.

---

sigma9.css

The current CSS leads to footnotes floating too high and into the next line. This is a change back to the original CSS before this bug appeared.

Footnote Fix

---

sigma9.css

Mostly whitespace. This maintains the unindentations within `@media` queries.

Format sigma code

---

sigma9.css

A misplaced bracket moved the interwiki CSS into a @media query and broke it. This fix puts the } where it is supposed to be.

Interwiki Fix

---

sigma9.css

Recieved a report that sidebar scroll was not working on mobile Firefox. Was able to reproduce on mobile Firefox 68.5.0 and desktop Firefox Developer 73.0b12. Works fine in Chromium.
Adding `overscroll-behavior: none` to `#side-bar` appears to fix this.

Fix sidebar scrolling on Firefox

---

sigma9.css

This is a technical change which alters how the different colors on the side-bar are achieved, allowing for easier/targeted alteration of those divs on individual themes without having to rely on !important tags. This both makes it easier for users to alter the elements themselves, and removes style elements from the site function. Nothing will change on the user end.
If implemented, the following changes would be made to nav:side (http://www.scp-wiki.net/nav:side):
From:
```
[[div class="side-block" style="background-color: #e5e5ff;"]]
```
To:
```
[[div class="side-block media"]]
```
From:
```
[[div class="side-block" style="background-color: #fff0f0;"]]
```
To:
```
[[div class="side-block resources"]]
```

Update to Side-Bar Colors

---

sigma9.css

Going back as far as https://web.archive.org/web/20150606072324/http://scp-wiki.wdfiles.com/local--files/component%3Atheme/dot.png there is no record of dot.png
Given we've gone this far without needing it, we should just remove it
from the CSS.

Remove nonexistant dot.png

---

sigma9.css

Currently, the burger stack button that opens the side-bar is coded with the following (some lines trimmed for conciseness).
```css
.open-menu a {
border: 0.2em solid #888 !important;
background-color: #fff !important;
color: #888 !important;
}
.open-menu a:hover {
text-decoration: none !important;
}
```
This uses four !important tags. These tags are necessary because the CSS used to style the top-bar links in general is more specific (using `#top-bar a`) than the code used to code the burger stack. By changing the selector and putting a `#top-bar` before `.open-menu a`, the correct order will be established, and the !important tags can be removed.

Remove !important tags from Sigma-9

---

README.md

I was also considering whether to use the HTTPS `scp-wiki.wikidot.com` URL.

Update SCP Wiki URL in the README

---

.github/workflows/stylelint.yaml
.stylelintrc.yaml
README.md
sigma9.css

We don't really have a "compiler", but a CSS linter should help ensure the quality of the CSS we're pushing to Sigma-9.
This PR:
* Adds a stylelint configuration file
* Adjusts the CSS according to the resultant lints
* Adds a GitHub actions step to ensure the file meets lint standards
* Adds the above badge to the README

Add stylelint

---

sigma9.css

Add a class to Sigma-9 that allows users to create a div that mimics the appearance of the standard page parenting links at the top of the page, so they can create the appearance of making their page look like it has been parented to multiple pages. Used as follows:
```css
[[div class="pseudocrumbs"]]
[[[Groups Of Interest]]] » [[[marshall-carter-and-dark-hub|Marshall, Carter and Dark Hub]]] » 'Night's Collection' (Lot C3S81)
[[[Groups Of Interest]]] » [[[chicago-spirit|GOI-001: Chicago Spirit]]] » [[[black-as-night|Black As Night Hub ]]] » 'Night's Collection' (Lot C3S81)
[[/div]]
```

Psuedocrumbs

---

sigma9.css

Many users like to change the title that appears on their pages, so that they are not a 1:1 match to the url or Wikidot page name. This has been used on a number of articles with consistent CSS, and adding it to Sigma-9 would allow it to be more uniformly used.

Add a CSS Class for Fake Titles

---

sigma9.css

Given that the Licensebox is expected to go on every Wiki page at some point, the necessary CSS to code it should be moved out of the component and into Sigma-9 as a whole.
This change also renames the class, from the previous "licensebox22" to the simpler and clearer "licensebox", removing the unnecessary number, which referred to CityToast's draft number.

Add CSS Class for Licensebox to Sigma-9

---

sigma9.css

The current height of the interwiki module often leaves ugly scrollbars - a vertical scrollbar to indicate that there is not enough vertical height, and then a horizontal scrollbar to indicate that there is not enough horizontal width after the width of the vertical scrollbar has claimed what it wants.
This PR bumps the interwiki height up to 350px, which is enough to cover all the currrent translation sites.
This is not a long-term solution. As more translation sites are created, the interwiki box will need to grow ever taller and taller.

Increase interwiki height to remove scrollbars

---

sigma9.css

Push the CSS module within the Sidebar for the recent Navigation Redesign back into Sigma-9.
"font-size: 90%" inline styling will be changed to class="menu-item small".

Incorporating new sidebar changes into mainline.

---

sigma9.css

Top bar a has side padding, of 1em up unti 385x, where an @ change it to 0.5em. This creates an odd gap between 385px and ~440px whre the top bar links breaks line. 
This remove the relevant at rule and compacts it with min()

Hot fix for mobile top bar space break.

---

sigma9.css

Remove some questionable CSS properties from #top-bar ul li a and made some minor padding changes for a near-identical appearance with less clunky CSS.
Do not commit until changes can confirm to not mess with dependent themes, but repercussions are likely very limited.

Clean up unintuitive top bar CSS.

---

sigma9.css

This should theoretically allow Sigma-9 to be imported to the new Interwiki (https://github.com/scpwiki/interwiki) without needing any sort of custom extra theme. This is the method of styling the new Interwiki that involves the least amount of effort.
Will mark as ready once I've tested with the new interwiki (dependent on the merge of scpwiki/interwiki#3).
EDIT: It works.

Extend sidebar styling to interwiki

---

sigma9.css

#side-bar:target contains some redundant css that can removed for simplcity. Border that only appears here are also removed.

remove redundant css from side-bar:target

---

sigma9.css

This is a re-approach to https://github.com/scpwiki/sigma9/pull/43, by adding a 5px bump to each side using negative margin. 
Resolving this as a preliminary step for the font change.

Correctly align interwiki with sidebar, again

---

sigma9.css

As suggested in https://github.com/scpwiki/sigma9/pull/26.
Personal testing and observation saw that removing word-break: break-all has little negative effect on mobile page display.
However, it does have a niche utility in preventing links from extending beyond screen boundary, which can be more handled deftly handled with overflow-wrap instead.

Replace word-break with overflow-wrap

---

sigma9.css

The height of the top bar is tied to the header image, which is around 21-22px.
This is fixed to line height to be independent of font size.

top bar link line height

---

sigma9.css

As Wikidot Search remains broken, and Crom search no longer has the redirect to retrieve the inputs of this field, the search bar input field should be hidden to prevent confusion.

Remove Search Bar Input Field

---

.github/workflows/deploy.yaml
.github/workflows/stylelint.yaml
.gitignore
README.md
build.sh
misc/.gitattributes
misc/error.html
misc/index.html
package-lock.json
package.json

Whenever a new change to Sigma-9 is pushed, this new GitHub workflow will take the changes and publish the files to https://scpwiki.github.io/sigma9/. The output of `gh-pages` after a build can be seen by looking at the [`build-system-out`](https://github.com/scpwiki/sigma9/tree/build-system-out) branch.
This won't change EN's theme deployment scheme until the URL is adjusted in the admin panel. We can launch this first, check for issues, then make the switch-over at our leisure.

Add automated workflow-based build system

---

sigma9.css

.heading has a default top margin of 10px, which creates unnecessary gap if it's the first item in the block.

no top margin for first child heading

---

sigma9.css

.scp-image-block img and .scp-image-caption has width set on it, which is both unnecessary and cause additional overheads

remove unneeded default width on imageblock childs

---

sigma9.css

Sigma-9 currently alters scrollbar appearance with the non-standard `::-webkit-` pseudo-elements.
This is both incompatible with Firefox and a (admittedly small) accessibility obstacle. In my opinion, it is better to not touch the scrollbar at all and let the UA handle it.
On Safari and most Chromium browsers, this will result in slightly less horizontal space.

Remove scrollbar CSS

---

.github/workflows/deploy.yaml
.github/workflows/lint.yaml
.github/workflows/stylelint.yaml
.prettierrc.toml
.stylelintrc.yaml
README.md
package-lock.json
package.json
sigma9.css

[Stylelint 15.0 was released](https://stylelint.io/migration-guide/to-15/), which brings with it deprecation of their formatting lints. After upgrading our tooling in `package.json`, I have added prettier as the new code formatter. I added options to make it closer to the existing style, but some changes were needed here.
Additionally, I have renamed the "Stylelint" flow to simply "Lint" and added the prettier check there via direct npm commands. Consequently, I have updated the badge and instructions in the README. There was an [issue with previous builds](https://github.com/scpwiki/sigma9/actions/runs/4594587438/jobs/8113796187) where an outdated GH workflow step was causing the build to not run.

Update development tools / CI workflow

---

sigma.css

Remove :visited from the selectors, as #side-bar a has high enough specificity.
Moved to side-bar section.

sidebar link color

---

.github/workflows/lint.yaml

Custom node is unnecessary and slows the process down. If this build passes, the PR is good to go.

Remove separate node setup

---

sigma.css

Fix an edge case where an img wont fill image block width if its intrinsic size is less than

set img block img to 100%

---

.github/workflows/deploy.yaml

One known issue with `cdn.scpwiki.com` has been the incorrect application of charsets onto uploaded files, causing any non-ASCII characters to render incorrectly.
This is tracked in https://github.com/aws/aws-cli/issues/1346. It seems clear that Amazon is not going to release a fix, so I have created https://github.com/emmiegit/s3-sync-action. This new action is a script which uploads each file separately, allowing us to detect and specify the MIME explicitly. This should fix the encoding issue and allow us to prepare to use the CDN for real.
I tested this using the dummy `scp-wiki-cdn-test` bucket, and confirmed that the expected file layout was present.

Fix text encoding issue for CDN

---

sigma.css

Reorganize .close-menu properties to minimize specificity spillover.
Remove useless(?) ::after element on side-bar.
Possibly breaking changes. Don't merge yet until verified.

close-menu optimization

---

sigma.css

`overflow-wrap` should be a more universally applied property - I've moved it to #main-content outside the media query (body was considered, but I wanted to avoid possible layout shift with #header and #side-bar)
Here's a simulated screenshot:
With:

move overflow-wrap property

---

sigma.css

Fix SVG backgrounds in header on IE by explicitly setting full background-size

---

sigma.css

Reverts scpwiki/sigma#93
According to @SYwaves:
> Do not merge
> We don’t want to add explicit sizing to bg size since it css change some pages on site that rely on intrinsic size of image
> We also dropped ie support already, so it didn’t matter much

Revert "Fix SVG backgrounds in header on IE by explicitly setting full background-size"

---

.github/workflows/deploy.yaml
build.sh

This invalidates the `/*` of the path, not just the root. It also adds a check to make sure the minified file was generated.

Invalidate CDN paths properly

---

sigma.css

nanum gothic too big for its only significant use; replaced with a (hopefully) websafe stack. Edit stack if found to be missing coverage later.

Remove nanum gothic from immediate stack

---

.github/workflows/deploy.yaml

\+ moved certain steps to more "conventional" well-updated actions
The actions/deploy-pages action expects to be run inside the "github-pages" environment, but it should autoconfigure this for you. But this means all variables and secrets should also be set in this environment.
---
Additional setup for DigitalOcean:
- Sign up for an account (and optionally, [create a new team](https://cloud.digitalocean.com/account/team/create))
- Create a [new space](https://cloud.digitalocean.com/spaces/new) and enable the CDN (be warned this starts billing you immediately). The name of the bucket should be stored in `vars.AWS_S3_BUCKET`.
- The region you create the space in determines the value for `vars.DIGITALOCEAN_SPACES_REGION`.
- Go to [personal access …

Update deploy workflow to use DigitalOcean Spaces.

---

sigma.css

Add Inter as a non-variable font fallback/Alias for system installed font; and Times New Roman as a preferred fallback on sidebar button for iOS devices.

fontstack addition

---

sigma.css

The block of footnotes at the bottom of the page does not wrap the footnotes into either a `<li>` or `<p>` element, causing it to not inherit the `line-height: 1.5` that paragraphs get by default. This applies that line-height argument to both the footnotes at the bottom of the page and the to the footnote blocks themselves, so it is not compressed.
Footnotes of SCP-3477 at present, in which footnote two gets the line-spacing because of the multiple paragraphs in the footnote, but in which the other footnotes do not have the line spacing.
Footnotes of SCP-3477 after line-spacing applied to `.footnote-footer`.
Current implementation of a footnote hovertip.
Footnote after change.

Adjust Line Height for Footnote Block

---

sigma.css

Setting up the pull request to return the site logo to the standard version on July 1st, 2025.

Post Pride Month Logo Reversion

---

sigma.css

Some recent changes did not conform to the stylelint and prettier styles, which are fixed here. I also make the whitespace in the file consistent.

Fix failing CI checks
