scpwiki/sigma

- sigma9.css
http://05command.wikidot.com/forum/t-7185049/proposed-recolor-of-visited-links
> Add a:visited color

- sigma9.css
Missing semicolon on Line 150 caused the next property not to parse correctly.
> A very important semicolon. Thanks stormbreath.

- sigma9.css
> Fix div typo

- sigma9.css
Demo: http://scptestwiki.wikidot.com/sigma:blockquotes
Desktop:
Mobile:
> Add class for curved blockquotes

- sigma9.css
Reported by @TSATPWTCOTTTADC 	
**Broken:**
**Fixed:** (as appears on [DE](http://scp-wiki-de.wikidot.com/system:recent-changes))
> Fix revision history column display on mobile

- sigma9.css
Theme update to make the theme both match the mainsite and remove any mistakes errors, such as:
- Empty Lines & Media Queries.
- Arguments & values that have been commented out.
- Values that were misspelled or invalid.
- Returned the @imports to the top of the page, so everything functions.
> Theme Update

- sigma9.css
This commit updates the stylesheet to use https links where appropriate as HTTPS has been enabled for the site.
> Change links to https

- sigma9.css
For consistency and cleanliness.
> Quote URLs in CSS

- sigma9.css
Add the CSS necessary for the Adult Content Warnings, as per this thread: http://05command.wikidot.com/forum/t-13896072/adult-content-warnings
Do not merge this pull until the vote here passes: http://05command.wikidot.com/forum/t-13929755/voting-thread-adult-content-warnings
> Adult Content Warning CSS

- sigma9.css
Condenses the various media queries previously optimized for a series of screen size ranges into two: (max-width: 767px) and (max-width: 479px). Other queries have been moved to appropriate locations as well.
This is to reduce code complexity and better maintainability.
> Consolidate media queries to 2 standard max-widths

- sigma9.css
not messing up this time
see http://mast-nav.wikidot.com/rate-point:theme for working demo
> remove need for important in rate module

- sigma9.css
Adding forum lines per Tech Team discussion
> Adding forum lines

- sigma9.css
Removed avatar hover, per Tech Team discussion.
> Remove avatar hover

- sigma9.css
Removed HTML color code, replaced hexcode with rgba
> Fixing forum lines

- README.md
- build.sh
- misc/index.html
- package.json
- sigma.css
SVG for logo, jsdelivr for deliver
> swapping to svg and jsdelivr

- images/header-logo-pride.svg
- sigma.css
Thanks to @SYwaves for creating the logo on short notice!
> Add SVG pride logo to source, use for June

- .github/workflows/deploy.yaml
Non-sensitive, and a minor workflow change.
> Use regular variables for AWS_REGION and AWS_S3_REGION

- sigma.css
Remove prefixes on properties with more than 95% compatibility, and othe minor changes
> cleanup properties and fix some minor stuff

- images/header-logo-trans.svg
Add trans version of the SVG logo
> SCP trans pride flag logo, vector

- sigma.css
Localized the relevant CSS on the component, and removed it from the theme.
> remove preview css from sigma

- sigma.css
Change the logo to the trans pride version for Trans Day of Visibility
> Trans Day of Visibility

- sigma.css
> Revert "Trans Day of Visibility" now that it's April

- sigma.css
> fix upload pane

- sigma.css
Reverts scpwiki/sigma#101
For end of pride month.
> Change logo back to normal

- .github/workflows/deploy.yaml
Created this branch to fix any issues with the action file, but the only change needed was a minor order adjustment.
> New CDN workflow updates

- sigma.css
Added CSS to style specific element that has a typo in the Wikidot code itself.
> Fixed Visual Issue on Flag User page across Sigma10

- sigma.css
> Change logo for TDOV 2025

- sigma.css
Reverts scpwiki/sigma#113
Merge _after_ end of TDOV.
> Revert "Change logo for TDOV 2025"

- sigma.css
Pride Logo for month of June as per standard.
> Pride Logo June 2025
